### ISSUE TITLE
No Mending Librarians

### ISSUE THREAD

**Issue by mrGRINCH** [SFort/MC-nomend#1]
Sorry for creating an issue, I couldn't find any other way to contact you.

Would you be able to make a mod that removes the mending trade from librarians but leaves the other ways of obtaining it in the game still?

**Comment by SFort** [comment]
opening a issue is fine
and ye sure i'll take a look at it

**Comment by mrGRINCH** [comment]
Thank you so much! I've been looking all over and couldn't find one anywhere.

**Comment by SFort** [comment]
[well that was easy](https://github.com/SFort/MC-nomend/releases/download/tagg/quickfix_nomendtrade-1.0.0.jar)

**Comment by mrGRINCH** [comment]
Wow that was fast. Thank you so much!
